### ISSUE TITLE
COM connection Android app

### ISSUE THREAD

**Issue by Snap1202** [voroshkov/Chorus-RF-Laptimer#72] opened 2017-11-14 14:28 UTC
is it possible to add com connection to the android app? I would like to use a 3dr Radio 433mhz as link to the unit as the bluetooth connection isnt working reliable for me. But Android app only shows WIFI or Bluetooth as option.

**Comment by voroshkov** [comment] 2017-11-15 08:29
I'd definitely work on this, but don't have an Android phone with OTG support yet.

**Comment by voroshkov** [comment] 2018-04-27 09:03
Duplicate of #43

**Closed by voroshkov** 2018-04-27 09:03 UTC
Labels: Android App, feature request
