### ISSUE TITLE
APP fix - not working with more than 4 units

### ISSUE THREAD

**Issue by romanas** [voroshkov/Chorus-RF-Laptimer#34] opened 2017-06-30 21:53 UTC
If connected 5 or 6 units, Android app, can controll only 4 first, 5ft unit will change 1 unit values, 6th unit not changing band/channel (tested with 9600 and 57600 baud rate)

**Comment by voroshkov** [comment] 2017-07-01 05:15
Duplicate of #22

**Closed by voroshkov** 2017-07-01 05:15 UTC
Labels: duplicate
