### ISSUE TITLE
TIMED RACE OPTION for rc buggies

### ISSUE THREAD

**Issue by ivkostic** [voroshkov/Chorus-RF-Laptimer#70] opened 2017-10-30 11:06 UTC
Hi! Great features so far! We tried it on the rc track for buggies, and is working superb! Only needed option for time limit for counting the laps/best lap. Can it be added 5 10 15 20 and 30 min of race, for counting the laps? This can be very usefull for rc car training

**Comment by ivkostic** [comment] 2017-10-30 11:10
ops i just saw an other topic with the similar header, this should be posted there.

**Comment by voroshkov** [comment] 2017-10-30 11:10
Wow! Are you using 5.8GHz VTx's just for laps tracking?

**Comment by ivkostic** [comment] 2017-10-30 11:12
yes  and it is perfect! we have a tons of ideas for buggy racing

**Comment by ivkostic** [comment] 2017-10-30 11:19
https://www.youtube.com/watch?v=KWu0FfP6fwM

**Comment by lazar89nis** [comment] 2017-10-30 12:00
Hi Andrey,

I wanted to show them how cool is you Android app for quadcopter racing and they took my device and started racing cars with it  :)

I can implement that part in iOS app but they only have android devices that is why i sent them to you :D

**Comment by voroshkov** [comment] 2017-11-01 11:06
Guys, sorry, but so far I don't have plans to extend the functionality of the Android app in this direction. Feel free to contribute and extend it.

**Comment by voroshkov** [comment] 2018-04-27 09:07
duplicate of #21

**Closed by voroshkov** 2018-04-27 09:07 UTC
Labels: Android App, feature request
